model: "tic_promptmodel"
dataset_path: '/path/to/dataset'
test_batch_size: 16
aux_learning_rate: 1.e-3
cuda: True
gpu_id: 0
save: True
name: "NAME"
exp_name: "NAME"
seed: 42
root: "./"
checkpoint: "checkpoint.pth.tar"
LOCATION: 'prepend'
DEEP: True
NUM_TOKENS: 16
INITIATION: 'random'
PROJECT: -1
DROPOUT: 0.
TRANSFER_TYPE: 'prompt'
ARCHITECT: 'both'
WINDOW: 'same' 
RETURN_ATTENTION: False
MASK_DOWNSAMPLE: 2